
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.util.LinkedList;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonIOException;
import com.google.gson.JsonSyntaxException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author nevfe
 */
public class MainForm extends javax.swing.JFrame {

    private final Gson gson;
    private String FilenameCar = "dataCars.json";
    private String FilenameCustomer = "dataCustomers.json";

    public void LoadLists() {
        try {
            readCarsFromJSON(Car[].class);
            readCustomersFromJSON(Customer[].class);

        } catch (IOException | JsonIOException | JsonSyntaxException ex) {
        }
    }

    public void SaveLists() {
        try {
            writeCustomersToJSON();
            writeCarsToJSON();
        } catch (IOException | JsonIOException | JsonSyntaxException ex) {
        }
    }

    public void writeCustomersToJSON() throws IOException, JsonIOException {
        try ( FileWriter fileWriter = new FileWriter(FilenameCustomer)) {
            gson.toJson(customerList, fileWriter);
        }
    }

    public void readCustomersFromJSON(java.lang.reflect.Type type) throws IOException, JsonIOException, JsonSyntaxException {
        try ( FileReader fileReader = new FileReader(FilenameCustomer)) {
            customerList = new LinkedList<Customer>(Arrays.asList(gson.fromJson(fileReader, type)));
        }
    }

    public void writeCarsToJSON() throws IOException, JsonIOException {
        try ( FileWriter fileWriter = new FileWriter(FilenameCar)) {
            gson.toJson(carList, fileWriter);
        }
    }

    public void readCarsFromJSON(java.lang.reflect.Type type) throws IOException, JsonIOException, JsonSyntaxException {
        try ( FileReader fileReader = new FileReader(FilenameCar)) {
            carList = new LinkedList<Car>(Arrays.asList(gson.fromJson(fileReader, type)));
        }
    }
    static List<Car> carList = new ArrayList<Car>();
    static List<Customer> customerList = new ArrayList<Customer>();

    //buraya araç ekleme panelinden gelinmiş.
    public MainForm(Car car) {
        initComponents();
        gson = new GsonBuilder().setPrettyPrinting().create();
        UpdateCars(car);
        UpdateCustomers();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        ShowAraclar();
    }

    //buraya müşteri ekleme panelinden gelinmiş.
    public MainForm(Customer customer) {
        initComponents();
        gson = new GsonBuilder().setPrettyPrinting().create();
        UpdateCustomers(customer);
        UpdateCars();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        ShowMusteriler();
    }

    // buraya gelmek için geri butonuna basılmış
    public MainForm(String whichPanel) {
        initComponents();
        gson = new GsonBuilder().setPrettyPrinting().create();
        UpdateCustomers();
        UpdateCars();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
        switch (whichPanel) {
            case "MA":
                ShowMusaitAraclar();
                break;

            case "M":
                ShowMusteriler();
                break;

            case "A":
                ShowAraclar();
                break;
        }
    }

    //İlk burası çalıştırılır.
    public MainForm() {
        initComponents();
        gson = new GsonBuilder().setPrettyPrinting().create();
        LoadLists();
        UpdateCustomers();
        UpdateCars();
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        ShowMusaitAraclar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidePanel = new javax.swing.JPanel();
        musaitAraclarPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kullanimdakiAraclarPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        musterilerPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        araclarPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        layeredPane = new javax.swing.JLayeredPane();
        MA_contentPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        kiralaPanel = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        KA_contentPanel = new javax.swing.JPanel();
        titlePanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        teslimEtPanel = new javax.swing.JPanel();
        jLabel63 = new javax.swing.JLabel();
        jLabel64 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        M_contentPanel = new javax.swing.JPanel();
        titlePanel2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        musteriCikarPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        musteriEklePanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel28 = new javax.swing.JLabel();
        musteriGecmisiPanel = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        A_contentPanel = new javax.swing.JPanel();
        titlePanel3 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        aracCikarPanel = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        aracEklePanel = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });

        sidePanel.setBackground(new java.awt.Color(21, 25, 101));
        sidePanel.setForeground(new java.awt.Color(21, 25, 101));

        musaitAraclarPanel.setBackground(new java.awt.Color(35, 68, 131));
        musaitAraclarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musaitAraclarPanelMousePressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_tick_box_24px_3.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Müsait Araçlar");

        javax.swing.GroupLayout musaitAraclarPanelLayout = new javax.swing.GroupLayout(musaitAraclarPanel);
        musaitAraclarPanel.setLayout(musaitAraclarPanelLayout);
        musaitAraclarPanelLayout.setHorizontalGroup(
            musaitAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musaitAraclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musaitAraclarPanelLayout.setVerticalGroup(
            musaitAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musaitAraclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musaitAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        kullanimdakiAraclarPanel.setBackground(new java.awt.Color(28, 31, 131));
        kullanimdakiAraclarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kullanimdakiAraclarPanelMousePressed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_sand_watch_24px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("Kullanımdaki Araçlar");

        javax.swing.GroupLayout kullanimdakiAraclarPanelLayout = new javax.swing.GroupLayout(kullanimdakiAraclarPanel);
        kullanimdakiAraclarPanel.setLayout(kullanimdakiAraclarPanelLayout);
        kullanimdakiAraclarPanelLayout.setHorizontalGroup(
            kullanimdakiAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kullanimdakiAraclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kullanimdakiAraclarPanelLayout.setVerticalGroup(
            kullanimdakiAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kullanimdakiAraclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kullanimdakiAraclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        musterilerPanel.setBackground(new java.awt.Color(28, 31, 131));
        musterilerPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musterilerPanelMousePressed(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_user_24px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Müşteriler");

        javax.swing.GroupLayout musterilerPanelLayout = new javax.swing.GroupLayout(musterilerPanel);
        musterilerPanel.setLayout(musterilerPanelLayout);
        musterilerPanelLayout.setHorizontalGroup(
            musterilerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musterilerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musterilerPanelLayout.setVerticalGroup(
            musterilerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musterilerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musterilerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        araclarPanel.setBackground(new java.awt.Color(28, 31, 131));
        araclarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                araclarPanelMousePressed(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_car_24px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Araçlar");

        javax.swing.GroupLayout araclarPanelLayout = new javax.swing.GroupLayout(araclarPanel);
        araclarPanel.setLayout(araclarPanelLayout);
        araclarPanelLayout.setHorizontalGroup(
            araclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(araclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        araclarPanelLayout.setVerticalGroup(
            araclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, araclarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(araclarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("Araç Kiralama");

        jLabel13.setFont(new java.awt.Font("ScriptC", 2, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Made by Nevfel Emre ÇIÇEK");

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(musaitAraclarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kullanimdakiAraclarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(musterilerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(araclarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(66, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addContainerGap())
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(musaitAraclarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(kullanimdakiAraclarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(musterilerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(araclarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227)
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MA_contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        MA_contentPanel.setPreferredSize(new java.awt.Dimension(884, 629));

        titlePanel.setBackground(new java.awt.Color(70, 181, 209));
        titlePanel.setPreferredSize(new java.awt.Dimension(842, 100));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Müsait Araçlar________________________");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanelLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plaka", "Vites", "Yakıt", "Renk", "Marka", "Model", "Yıl"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowSorter(null);
        jTable1.setShowGrid(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 25, 101));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("X");
        jLabel4.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        kiralaPanel.setBackground(new java.awt.Color(28, 31, 131));
        kiralaPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kiralaPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                kiralaPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                kiralaPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                kiralaPanelMouseReleased(evt);
            }
        });

        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_checked_checkbox_30px_1.png"))); // NOI18N

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setText("Kirala");

        javax.swing.GroupLayout kiralaPanelLayout = new javax.swing.GroupLayout(kiralaPanel);
        kiralaPanel.setLayout(kiralaPanelLayout);
        kiralaPanelLayout.setHorizontalGroup(
            kiralaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kiralaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        kiralaPanelLayout.setVerticalGroup(
            kiralaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kiralaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kiralaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText(" ");

        javax.swing.GroupLayout MA_contentPanelLayout = new javax.swing.GroupLayout(MA_contentPanel);
        MA_contentPanel.setLayout(MA_contentPanelLayout);
        MA_contentPanelLayout.setHorizontalGroup(
            MA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MA_contentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(MA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MA_contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 844, Short.MAX_VALUE)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MA_contentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MA_contentPanelLayout.createSequentialGroup()
                            .addComponent(kiralaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(42, 42, 42)))))
        );
        MA_contentPanelLayout.setVerticalGroup(
            MA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MA_contentPanelLayout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(kiralaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        KA_contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        KA_contentPanel.setPreferredSize(new java.awt.Dimension(884, 629));

        titlePanel1.setBackground(new java.awt.Color(70, 181, 209));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("  Kullanımdaki Araçlar_________________");

        javax.swing.GroupLayout titlePanel1Layout = new javax.swing.GroupLayout(titlePanel1);
        titlePanel1.setLayout(titlePanel1Layout);
        titlePanel1Layout.setHorizontalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 843, Short.MAX_VALUE)
        );
        titlePanel1Layout.setVerticalGroup(
            titlePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plaka", "Vites", "Yakıt", "Renk", "Marka", "Model", "Yıl", "Kullanan Kişi", "Başlangıç Tarihi", "Bitiş Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowSorter(null);
        jTable2.setShowGrid(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(21, 25, 101));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("X");
        jLabel16.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel16MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel16MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel16MousePressed(evt);
            }
        });

        teslimEtPanel.setBackground(new java.awt.Color(28, 31, 131));
        teslimEtPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teslimEtPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teslimEtPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teslimEtPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                teslimEtPanelMouseReleased(evt);
            }
        });

        jLabel63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_hotel_room_key_30px.png"))); // NOI18N

        jLabel64.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel64.setForeground(new java.awt.Color(255, 255, 255));
        jLabel64.setText("Teslim Et");

        javax.swing.GroupLayout teslimEtPanelLayout = new javax.swing.GroupLayout(teslimEtPanel);
        teslimEtPanel.setLayout(teslimEtPanelLayout);
        teslimEtPanelLayout.setHorizontalGroup(
            teslimEtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teslimEtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel63, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        teslimEtPanelLayout.setVerticalGroup(
            teslimEtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, teslimEtPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(teslimEtPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel14.setForeground(new java.awt.Color(153, 153, 153));
        jLabel14.setText(" ");

        javax.swing.GroupLayout KA_contentPanelLayout = new javax.swing.GroupLayout(KA_contentPanel);
        KA_contentPanel.setLayout(KA_contentPanelLayout);
        KA_contentPanelLayout.setHorizontalGroup(
            KA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KA_contentPanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(KA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlePanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(KA_contentPanelLayout.createSequentialGroup()
                        .addGroup(KA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(KA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(teslimEtPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        KA_contentPanelLayout.setVerticalGroup(
            KA_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(KA_contentPanelLayout.createSequentialGroup()
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel14)
                .addGap(2, 2, 2)
                .addComponent(teslimEtPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        M_contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        M_contentPanel.setPreferredSize(new java.awt.Dimension(884, 629));

        titlePanel2.setBackground(new java.awt.Color(70, 181, 209));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Müşteriler_____________________________");

        javax.swing.GroupLayout titlePanel2Layout = new javax.swing.GroupLayout(titlePanel2);
        titlePanel2.setLayout(titlePanel2Layout);
        titlePanel2Layout.setHorizontalGroup(
            titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addContainerGap())
        );
        titlePanel2Layout.setVerticalGroup(
            titlePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        musteriCikarPanel.setBackground(new java.awt.Color(28, 31, 131));
        musteriCikarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musteriCikarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musteriCikarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musteriCikarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                musteriCikarPanelMouseReleased(evt);
            }
        });

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_subtract_30px.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Çıkar");

        javax.swing.GroupLayout musteriCikarPanelLayout = new javax.swing.GroupLayout(musteriCikarPanel);
        musteriCikarPanel.setLayout(musteriCikarPanelLayout);
        musteriCikarPanelLayout.setHorizontalGroup(
            musteriCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriCikarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        musteriCikarPanelLayout.setVerticalGroup(
            musteriCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteriCikarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musteriCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        musteriEklePanel.setBackground(new java.awt.Color(28, 31, 131));
        musteriEklePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musteriEklePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musteriEklePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musteriEklePanelMousePressed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_math_30px_1.png"))); // NOI18N

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Ekle");

        javax.swing.GroupLayout musteriEklePanelLayout = new javax.swing.GroupLayout(musteriEklePanel);
        musteriEklePanel.setLayout(musteriEklePanelLayout);
        musteriEklePanelLayout.setHorizontalGroup(
            musteriEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriEklePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        musteriEklePanelLayout.setVerticalGroup(
            musteriEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteriEklePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musteriEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İsim", "Soyisim", "T.C. Kimlik No", "Kiraladığı Plaka", "Başlangıç Tarihi", "Bitiş Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setGridColor(new java.awt.Color(255, 255, 255));
        jTable3.setRowSorter(null);
        jTable3.setShowGrid(false);
        jTable3.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTable3);

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(21, 25, 101));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("X");
        jLabel28.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel28MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel28MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel28MousePressed(evt);
            }
        });

        musteriGecmisiPanel.setBackground(new java.awt.Color(28, 31, 131));
        musteriGecmisiPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                musteriGecmisiPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                musteriGecmisiPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                musteriGecmisiPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                musteriGecmisiPanelMouseReleased(evt);
            }
        });

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_order_history_30px.png"))); // NOI18N

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Müşteri Geçmişi");

        javax.swing.GroupLayout musteriGecmisiPanelLayout = new javax.swing.GroupLayout(musteriGecmisiPanel);
        musteriGecmisiPanel.setLayout(musteriGecmisiPanelLayout);
        musteriGecmisiPanelLayout.setHorizontalGroup(
            musteriGecmisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musteriGecmisiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        musteriGecmisiPanelLayout.setVerticalGroup(
            musteriGecmisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, musteriGecmisiPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(musteriGecmisiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel20.setForeground(new java.awt.Color(153, 153, 153));
        jLabel20.setText(" ");

        jLabel21.setForeground(new java.awt.Color(153, 153, 153));
        jLabel21.setText(" ");

        javax.swing.GroupLayout M_contentPanelLayout = new javax.swing.GroupLayout(M_contentPanel);
        M_contentPanel.setLayout(M_contentPanelLayout);
        M_contentPanelLayout.setHorizontalGroup(
            M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_contentPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(titlePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, M_contentPanelLayout.createSequentialGroup()
                        .addComponent(musteriEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addGroup(M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musteriGecmisiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(72, 72, 72)
                        .addGroup(M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(musteriCikarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(41, Short.MAX_VALUE))
                    .addGroup(M_contentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(41, 41, 41))))
            .addGroup(M_contentPanelLayout.createSequentialGroup()
                .addGap(857, 857, 857)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        M_contentPanelLayout.setVerticalGroup(
            M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(M_contentPanelLayout.createSequentialGroup()
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(1, 1, 1)
                .addGroup(M_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(musteriCikarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(musteriGecmisiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        A_contentPanel.setBackground(new java.awt.Color(255, 255, 255));
        A_contentPanel.setPreferredSize(new java.awt.Dimension(884, 629));

        titlePanel3.setBackground(new java.awt.Color(70, 181, 209));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Araçlar_________________________________");

        javax.swing.GroupLayout titlePanel3Layout = new javax.swing.GroupLayout(titlePanel3);
        titlePanel3.setLayout(titlePanel3Layout);
        titlePanel3Layout.setHorizontalGroup(
            titlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titlePanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel29))
        );
        titlePanel3Layout.setVerticalGroup(
            titlePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        aracCikarPanel.setBackground(new java.awt.Color(28, 31, 131));
        aracCikarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aracCikarPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aracCikarPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aracCikarPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                aracCikarPanelMouseReleased(evt);
            }
        });

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_subtract_30px.png"))); // NOI18N

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Çıkar");

        javax.swing.GroupLayout aracCikarPanelLayout = new javax.swing.GroupLayout(aracCikarPanel);
        aracCikarPanel.setLayout(aracCikarPanelLayout);
        aracCikarPanelLayout.setHorizontalGroup(
            aracCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aracCikarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        aracCikarPanelLayout.setVerticalGroup(
            aracCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aracCikarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aracCikarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        aracEklePanel.setBackground(new java.awt.Color(28, 31, 131));
        aracEklePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aracEklePanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aracEklePanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                aracEklePanelMousePressed(evt);
            }
        });

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_plus_math_30px_1.png"))); // NOI18N

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Ekle");

        javax.swing.GroupLayout aracEklePanelLayout = new javax.swing.GroupLayout(aracEklePanel);
        aracEklePanel.setLayout(aracEklePanelLayout);
        aracEklePanelLayout.setHorizontalGroup(
            aracEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aracEklePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        aracEklePanelLayout.setVerticalGroup(
            aracEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aracEklePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(aracEklePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTable4.setAutoCreateRowSorter(true);
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plaka", "Vites", "Yakıt", "Renk", "Marka", "Model", "Yıl", "Durum", "Başlangıç Tarihi", "Bitiş Tarihi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable4.setGridColor(new java.awt.Color(255, 255, 255));
        jTable4.setRowSorter(null);
        jTable4.setShowGrid(false);
        jTable4.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable4);

        jLabel34.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(21, 25, 101));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("X");
        jLabel34.setPreferredSize(new java.awt.Dimension(45, 45));
        jLabel34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel34MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel34MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel34MousePressed(evt);
            }
        });

        jLabel22.setForeground(new java.awt.Color(153, 153, 153));
        jLabel22.setText(" ");

        javax.swing.GroupLayout A_contentPanelLayout = new javax.swing.GroupLayout(A_contentPanel);
        A_contentPanel.setLayout(A_contentPanelLayout);
        A_contentPanelLayout.setHorizontalGroup(
            A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_contentPanelLayout.createSequentialGroup()
                .addGroup(A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(A_contentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, A_contentPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(A_contentPanelLayout.createSequentialGroup()
                                    .addComponent(aracEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(aracCikarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(titlePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(791, 791, 791))
        );
        A_contentPanelLayout.setVerticalGroup(
            A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(A_contentPanelLayout.createSequentialGroup()
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titlePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel22)
                .addGap(1, 1, 1)
                .addGroup(A_contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aracCikarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aracEklePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(426, Short.MAX_VALUE))
        );

        layeredPane.setLayer(MA_contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(KA_contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(M_contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        layeredPane.setLayer(A_contentPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layeredPaneLayout = new javax.swing.GroupLayout(layeredPane);
        layeredPane.setLayout(layeredPaneLayout);
        layeredPaneLayout.setHorizontalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KA_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(807, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(MA_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 897, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(807, Short.MAX_VALUE)))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(M_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(352, 352, 352)))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addComponent(A_contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1704, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layeredPaneLayout.setVerticalGroup(
            layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layeredPaneLayout.createSequentialGroup()
                .addComponent(KA_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 406, Short.MAX_VALUE))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPaneLayout.createSequentialGroup()
                    .addComponent(MA_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 652, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 400, Short.MAX_VALUE)))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layeredPaneLayout.createSequentialGroup()
                    .addComponent(M_contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
            .addGroup(layeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layeredPaneLayout.createSequentialGroup()
                    .addComponent(A_contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1046, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addGap(336, 336, 336)
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bgLayout.createSequentialGroup()
                    .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 1239, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        setLocation(getX() + evt.getX() - mouseX, getY() + evt.getY() - mouseY);
    }//GEN-LAST:event_bgMouseDragged

    private void araclarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_araclarPanelMousePressed
        ShowAraclar();
        UpdateCars();
    }//GEN-LAST:event_araclarPanelMousePressed

    private void musterilerPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musterilerPanelMousePressed
        ShowMusteriler();
        UpdateCustomers();
    }//GEN-LAST:event_musterilerPanelMousePressed

    private void kullanimdakiAraclarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kullanimdakiAraclarPanelMousePressed
        ShowKullanimdakiAraclar();
        UpdateCars();
    }//GEN-LAST:event_kullanimdakiAraclarPanelMousePressed

    private void musaitAraclarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musaitAraclarPanelMousePressed
        ShowMusaitAraclar();
        UpdateCars();
    }//GEN-LAST:event_musaitAraclarPanelMousePressed

    private void jLabel34MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MousePressed
        SaveLists();
        System.exit(0);
    }//GEN-LAST:event_jLabel34MousePressed

    private void jLabel34MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseExited
        resetForeground(jLabel34);
    }//GEN-LAST:event_jLabel34MouseExited

    private void jLabel34MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel34MouseEntered
        highlightForeground(jLabel34);
    }//GEN-LAST:event_jLabel34MouseEntered

    private void aracEklePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracEklePanelMousePressed
        new AddCarForm().setVisible(true);
        close();
    }//GEN-LAST:event_aracEklePanelMousePressed

    private void aracEklePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracEklePanelMouseExited
        resetColor(aracEklePanel);
    }//GEN-LAST:event_aracEklePanelMouseExited

    private void aracEklePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracEklePanelMouseEntered
        highlightColor(aracEklePanel);
    }//GEN-LAST:event_aracEklePanelMouseEntered

    private void aracCikarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracCikarPanelMousePressed
        try {
            DefaultTableModel tblModel4 = (DefaultTableModel) jTable4.getModel();
            int index = jTable4.getSelectedRow();
            String selectedAvailability = tblModel4.getValueAt(index, 7).toString();

            if (selectedAvailability.equals("Müsait")) {
                carList.remove(index);
                UpdateCars();
            } else {
                JOptionPane.showMessageDialog(this, "Bu araç kullanımda olduğu için çıkarılamaz !", "Uyarı", 0);
            }
        } catch (Exception e) {
            jLabel22.setText("Lütfen araç seçiniz");
        }
    }//GEN-LAST:event_aracCikarPanelMousePressed

    private void aracCikarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracCikarPanelMouseExited
        resetColor(aracCikarPanel);
    }//GEN-LAST:event_aracCikarPanelMouseExited

    private void aracCikarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracCikarPanelMouseEntered
        highlightColor(aracCikarPanel);
    }//GEN-LAST:event_aracCikarPanelMouseEntered

    private void musteriGecmisiPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriGecmisiPanelMousePressed
        try {
            DefaultTableModel tblModel3 = (DefaultTableModel) jTable3.getModel();
            int index = jTable3.getSelectedRow();
            String selectedName = tblModel3.getValueAt(index, 0).toString();
            String selectedSurname = tblModel3.getValueAt(index, 1).toString();
            String selectedID = tblModel3.getValueAt(index, 2).toString();

            new HistoryOfCustomer(selectedName, selectedSurname, selectedID).setVisible(true);
            close();
        } catch (Exception e) {
            jLabel20.setText("Lütfen müşteri seçiniz");
        }
    }//GEN-LAST:event_musteriGecmisiPanelMousePressed

    private void musteriGecmisiPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriGecmisiPanelMouseExited
        resetColor(musteriGecmisiPanel);
    }//GEN-LAST:event_musteriGecmisiPanelMouseExited

    private void musteriGecmisiPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriGecmisiPanelMouseEntered
        highlightColor(musteriGecmisiPanel);
    }//GEN-LAST:event_musteriGecmisiPanelMouseEntered

    private void jLabel28MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MousePressed
        SaveLists();
        System.exit(0);
    }//GEN-LAST:event_jLabel28MousePressed

    private void jLabel28MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseExited
        resetForeground(jLabel28);
    }//GEN-LAST:event_jLabel28MouseExited

    private void jLabel28MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseEntered
        highlightForeground(jLabel28);
    }//GEN-LAST:event_jLabel28MouseEntered

    private void musteriEklePanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriEklePanelMousePressed
        new AddCustomerForm().setVisible(true);
        close();
    }//GEN-LAST:event_musteriEklePanelMousePressed

    private void musteriEklePanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriEklePanelMouseExited
        resetColor(musteriEklePanel);
    }//GEN-LAST:event_musteriEklePanelMouseExited

    private void musteriEklePanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriEklePanelMouseEntered
        highlightColor(musteriEklePanel);
    }//GEN-LAST:event_musteriEklePanelMouseEntered

    private void musteriCikarPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriCikarPanelMousePressed
        try {
            DefaultTableModel tblModel3 = (DefaultTableModel) jTable3.getModel();
            int index = jTable3.getSelectedRow();
            String selectedAvailability = tblModel3.getValueAt(index, 3).toString();
            String selectedID = tblModel3.getValueAt(index, 2).toString();

            if (selectedAvailability.equals("---")) {
                customerList.remove(index);
                UpdateCustomers();
            } else {
                JOptionPane.showMessageDialog(this, "Bu kişi, kiraladığı aracı teslim etmeden çıkarılamaz !", "Uyarı", 0);
            }

        } catch (Exception e) {
            jLabel21.setText("Lütfen müşteri seçiniz");
        }
    }//GEN-LAST:event_musteriCikarPanelMousePressed

    private void musteriCikarPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriCikarPanelMouseExited
        resetColor(musteriCikarPanel);
    }//GEN-LAST:event_musteriCikarPanelMouseExited

    private void musteriCikarPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriCikarPanelMouseEntered
        highlightColor(musteriCikarPanel);
    }//GEN-LAST:event_musteriCikarPanelMouseEntered

    private void teslimEtPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teslimEtPanelMousePressed
        try {
            DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();
            int index = jTable2.getSelectedRow();
            String selectedNumberPlate = tblModel2.getValueAt(index, 0).toString();
            
            for (Car car : carList) {
                if (car.getNumberPlate().equals(selectedNumberPlate)) {

                    for (Customer customer : customerList) {
                        if (car.getUserID().equals(customer.getIdentity())) {
                            customer.changeAvailability();
                            customer.setNumberPlate("---");
                            customer.setDeadline("---");
                            customer.setStartDate("---");
                            customer.addToHistory(car);
                            break;
                        }
                    }
                    car.changeAvailability();
                    car.setUser("---");
                    car.setUserID("---");
                    car.setDeadline("---");
                    car.setStartDate("---");
                    break;
                }
            }
            UpdateCustomers();
            UpdateCars();
        } catch (Exception e) {
            jLabel14.setText("Lütfen araç seçiniz");
        }
    }//GEN-LAST:event_teslimEtPanelMousePressed

    private void teslimEtPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teslimEtPanelMouseExited
        resetColor(teslimEtPanel);
    }//GEN-LAST:event_teslimEtPanelMouseExited

    private void teslimEtPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teslimEtPanelMouseEntered
        highlightColor(teslimEtPanel);
    }//GEN-LAST:event_teslimEtPanelMouseEntered

    private void jLabel16MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MousePressed
        SaveLists();
        System.exit(0);
    }//GEN-LAST:event_jLabel16MousePressed

    private void jLabel16MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseExited
        resetForeground(jLabel16);
    }//GEN-LAST:event_jLabel16MouseExited

    private void jLabel16MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseEntered
        highlightForeground(jLabel16);
    }//GEN-LAST:event_jLabel16MouseEntered

    private void kiralaPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralaPanelMousePressed
        try {
            DefaultTableModel tblModel1 = (DefaultTableModel) jTable1.getModel();
            int index = jTable1.getSelectedRow();
            String selectedNumberPlate = tblModel1.getValueAt(index, 0).toString();

            new RentForm(selectedNumberPlate).setVisible(true);
            close();
        } catch (Exception e) {
            jLabel3.setText("Lütfen araç seçiniz");
        }
    }//GEN-LAST:event_kiralaPanelMousePressed

    private void kiralaPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralaPanelMouseExited
        resetColor(kiralaPanel);
    }//GEN-LAST:event_kiralaPanelMouseExited

    private void kiralaPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralaPanelMouseEntered
        highlightColor(kiralaPanel);
    }//GEN-LAST:event_kiralaPanelMouseEntered

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        SaveLists();
        System.exit(0);
    }//GEN-LAST:event_jLabel4MousePressed

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        resetForeground(jLabel4);
    }//GEN-LAST:event_jLabel4MouseExited

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        highlightForeground(jLabel4);
    }//GEN-LAST:event_jLabel4MouseEntered

    private void kiralaPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kiralaPanelMouseReleased
        jLabel3.setText(" ");
    }//GEN-LAST:event_kiralaPanelMouseReleased

    private void teslimEtPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teslimEtPanelMouseReleased
        jLabel14.setText(" ");
    }//GEN-LAST:event_teslimEtPanelMouseReleased

    private void musteriCikarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriCikarPanelMouseReleased
        jLabel21.setText(" ");
    }//GEN-LAST:event_musteriCikarPanelMouseReleased

    private void musteriGecmisiPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_musteriGecmisiPanelMouseReleased
        jLabel20.setText(" ");
    }//GEN-LAST:event_musteriGecmisiPanelMouseReleased

    private void aracCikarPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aracCikarPanelMouseReleased
        jLabel22.setText(" ");
    }//GEN-LAST:event_aracCikarPanelMouseReleased

    private void ShowMusaitAraclar() {
        MA_contentPanel.setVisible(true);
        KA_contentPanel.setVisible(false);
        M_contentPanel.setVisible(false);
        A_contentPanel.setVisible(false);
        setColor(musaitAraclarPanel);
        resetColor(kullanimdakiAraclarPanel);
        resetColor(musterilerPanel);
        resetColor(araclarPanel);
    }

    private void ShowKullanimdakiAraclar() {
        MA_contentPanel.setVisible(false);
        KA_contentPanel.setVisible(true);
        M_contentPanel.setVisible(false);
        A_contentPanel.setVisible(false);
        setColor(kullanimdakiAraclarPanel);
        resetColor(musaitAraclarPanel);
        resetColor(musterilerPanel);
        resetColor(araclarPanel);
    }

    private void ShowMusteriler() {
        MA_contentPanel.setVisible(false);
        KA_contentPanel.setVisible(false);
        M_contentPanel.setVisible(true);
        A_contentPanel.setVisible(false);
        setColor(musterilerPanel);
        resetColor(kullanimdakiAraclarPanel);
        resetColor(musaitAraclarPanel);
        resetColor(araclarPanel);
    }

    private void ShowAraclar() {
        MA_contentPanel.setVisible(false);
        KA_contentPanel.setVisible(false);
        M_contentPanel.setVisible(false);
        A_contentPanel.setVisible(true);
        setColor(araclarPanel);
        resetColor(kullanimdakiAraclarPanel);
        resetColor(musterilerPanel);
        resetColor(musaitAraclarPanel);
    }

    public void UpdateCars(Car car) {
        this.carList.add(car);
        UpdateCars();
    }

    public void UpdateCars() {
        DefaultTableModel tblModel1 = (DefaultTableModel) jTable1.getModel();//müsait araçlar
        DefaultTableModel tblModel2 = (DefaultTableModel) jTable2.getModel();//kullanılan araçlar
        DefaultTableModel tblModel4 = (DefaultTableModel) jTable4.getModel();//bütün araçlar

        // <editor-fold defaultstate="collapsed" desc="Müsait araçlar tablosu güncellemesi">  
        tblModel1.setRowCount(0);

        for (Car c : carList) {
            if (c.isAvailable()) {
                String data[] = {c.getNumberPlate(), c.getTransmissionType().toString(), c.getFuelType().toString(), c.getColor(), c.getBrand(), c.getModel(), c.getYear()};
                tblModel1.addRow(data);
            }
        }
        // </editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Kullanılan araçlar tablosu güncellemesi">  
        tblModel2.setRowCount(0);

        for (Car c : carList) {
            if (!c.isAvailable()) {
                String data[] = {c.getNumberPlate(), c.getTransmissionType().toString(), c.getFuelType().toString(), c.getColor(), c.getBrand(), c.getModel(), c.getYear(), c.getUser(), c.getStartDate(), c.getDeadline()};
                tblModel2.addRow(data);
            }
        }
        // </editor-fold>

        // <editor-fold defaultstate="collapsed" desc="Araçlar tablosu güncellemesi">  
        tblModel4.setRowCount(0);

        for (Car c : carList) {
            if (c.isAvailable()) {
                String data[] = {c.getNumberPlate(), c.getTransmissionType().toString(), c.getFuelType().toString(), c.getColor(), c.getBrand(), c.getModel(), c.getYear(), "Müsait", c.getStartDate(), c.getDeadline()};
                tblModel4.addRow(data);
            } else {
                String data[] = {c.getNumberPlate(), c.getTransmissionType().toString(), c.getFuelType().toString(), c.getColor(), c.getBrand(), c.getModel(), c.getYear(), "Kullanımda", c.getStartDate(), c.getDeadline()};
                tblModel4.addRow(data);
            }
        }
        // </editor-fold>
    }

    public void UpdateCustomers(Customer customer) {
        this.customerList.add(customer);
        UpdateCustomers();
    }

    public void UpdateCustomers() {
        DefaultTableModel tblModel3 = (DefaultTableModel) jTable3.getModel();

        tblModel3.setRowCount(0);

        for (Customer c : customerList) {
            String data[] = {c.getName(), c.getSurname(), c.getIdentity(), c.getNumberPlate(), c.getStartDate(), c.getDeadline()};
            tblModel3.addRow(data);
        }
    }

    public void close() {
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private int mouseX, mouseY;

    void highlightForeground(JLabel label) {
        label.setForeground(new java.awt.Color(70, 181, 209));
    }

    void resetForeground(JLabel label) {
        label.setForeground(new java.awt.Color(28, 31, 131));
    }

    void highlightColor(JPanel panel) {
        panel.setBackground(new Color(70, 181, 209));
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(35, 68, 131));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(28, 31, 131));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel A_contentPanel;
    private javax.swing.JPanel KA_contentPanel;
    private javax.swing.JPanel MA_contentPanel;
    private javax.swing.JPanel M_contentPanel;
    private javax.swing.JPanel aracCikarPanel;
    private javax.swing.JPanel aracEklePanel;
    private javax.swing.JPanel araclarPanel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel kiralaPanel;
    private javax.swing.JPanel kullanimdakiAraclarPanel;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JPanel musaitAraclarPanel;
    private javax.swing.JPanel musteriCikarPanel;
    private javax.swing.JPanel musteriEklePanel;
    private javax.swing.JPanel musteriGecmisiPanel;
    private javax.swing.JPanel musterilerPanel;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel teslimEtPanel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JPanel titlePanel1;
    private javax.swing.JPanel titlePanel2;
    private javax.swing.JPanel titlePanel3;
    // End of variables declaration//GEN-END:variables
}
